name: "Test"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_and_build:
    name: "Compile & Lint"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v4

    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        version-file: .tool-versions
        version-type: strict

    - run: |
        mix deps.get
        mix compile --warnings-as-errors
        mix lint
        mix test

  mutation_testing:
    name: "Mutation Testing"
    runs-on: "ubuntu-latest"
    needs: test_and_build
    steps:
    - uses: actions/checkout@v4

    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        version-file: .tool-versions
        version-type: strict

    - name: Run mutation testing
      run: mix deps.get && mix test && mix muex --fail-at 60

  mutation_testing_pr:
    name: "Mutation Testing (PR)"
    runs-on: "ubuntu-latest"
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4

    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        version-file: .tool-versions
        version-type: strict

    - name: Run mutation testing (PR)
      run: mix deps.get && mix test && mix muex
