name: "Test"
on: ["push", "pull_request"]

jobs:
  test_and_build:
    name: "Compile & Lint"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        version-file: .tool-versions
        version-type: strict

    - run: |
        mix deps.get
        mix compile --warnings-as-errors
        mix lint
        mix test
