name: "Test"
on: ["push", "pull_request"]

jobs:
  test_and_build:
    name: "Compile & Lint (OTP ${{ matrix.otp }})"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        include:
        - otp: "27"
          elixir: "1.17"
        - otp: "28"
          elixir: "1.18"
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - run: |
        mix deps.get
        mix compile --warnings-as-errors
        mix lint
        mix test
